export const mappedPlanetSentinels = [
  {
    groupLabel: 'Bajo',
    label: 'Bajo',
    items: [
      { label: 'Ausentes', value: 'Absent' },
      { label: 'Exiguo', value: 'Few' },
      { label: 'Poco frecuente', value: 'Infrequent' },
      { label: 'Intermitente', value: 'Intermittent' },
      { label: 'Patrullas irregulares', value: 'Irregular Patrols' },
      { label: 'Aislado', value: 'Isolated' },
      { label: 'Limitados', value: 'Limited' },
      { label: 'Bajo', value: 'Low' },
      { label: 'Seguridad baja', value: 'Low Security' },
      { label: 'Mínimo', value: 'Minimal' },
      { label: 'Desaparecido', value: 'Missing' },
      { label: 'Ninguno', value: 'None' },
      { label: 'Ninguno presente', value: 'None Present' },
      { label: 'No presente', value: 'Not Present' },
      { label: 'Remoto', value: 'Remote' },
      { label: 'Disperso', value: 'Sparse' },
      { label: 'Abarca demasiado', value: 'Spread Thin' },
    ],
  },
  {
    groupLabel: 'Alto',
    label: 'Alto',
    items: [
      { label: 'Atento', value: 'Attentive' },
      { label: 'Ejecutor', value: 'Enforcing' },
      { label: 'Constante', value: 'Ever-present' },
      { label: 'Frecuente', value: 'Frequent' },
      { label: 'Observador', value: 'Observant' },
      { label: 'Patrullas regulares', value: 'Regular Patrols' },
      { label: 'Requieren obediencia', value: 'Require Obedience' },
      { label: 'Requieren ortodoxia', value: 'Require Orthodoxy' },
      { label: 'Inquebrantable', value: 'Unwavering' },
    ],
  },
  {
    groupLabel: 'Agresivo',
    label: 'Agresivo',
    items: [
      { label: 'Agresivo', value: 'Aggressive' },
      { label: 'Enloquecido', value: 'Frenzied' },
      { label: 'Detestable', value: 'Hateful' },
      { label: 'Seguridad alta', value: 'High Security' },
      { label: 'Patrullas hostiles', value: 'Hostile Patrols' },
      { label: 'Inevitable', value: 'Inescapable' },
      { label: 'Malicioso', value: 'Malicious' },
      { label: 'Amenazante', value: 'Threatening' },
      { label: 'Fervoroso', value: 'Zealous' },
    ],
  },
  {
    groupLabel: 'Corruptos',
    label: 'Corruptos',
    items: [
      { label: 'Corrupto', value: 'Corrupted' },
      { label: 'Abandonado', value: 'Forsaken' },
      { label: 'Rebelde', value: 'Rebellious' },
      { label: 'Responder a nadie', value: 'Answer To None' },
      { label: 'Fragmentado del Atlas', value: 'Sharded from the Atlas' },
      { label: 'Disonante', value: 'Dissonant' },
      { label: 'Desarmonizado', value: 'De-Harmonised' },
    ],
  },
];
