import type { SelectOption } from '@/types/selectInputOptions';

const InEnglish = [
  'Dead Planet',
  'Empty Planet',
  'Desolate Planet',
  'Lifeless Planet',
  'Forsaken Planet',
  'Life-Incompatible Planet',
  'Low Atmosphere Planet',
  'Airless Planet',
  'Abandoned Planet',
  'Terraforming Catastrophe',
  'Rainy Planet',
  'Verdant Planet',
  'Tropical Planet',
  'Viridescent Planet',
  'Grassy Planet',
  'Temperate Planet',
  'Humid Planet',
  'Overgrown Planet',
  'Flourishing Planet',
  'Bountiful Planet',
  'Paradise Planet',
  'Shattered Planet',
  'Fractured Planet',
  'Fragmented Planet',
  'Contoured Planet',
  'Cabled Planet',
  'Webbed Planet',
  'Rattling Planet',
  'Spined Planet',
  'Skeletal Planet',
  'Finned Planet',
  'Bladed Planet',
  'Shell-Strewn Planet',
  'Fungal Planet',
  'Sporal Planet',
  'Capped Planet',
  'Ossified Planet',
  'Petrified Planet',
  'Calcified Planet',
  'Fissured Planet',
  'Breached Planet',
  'Hexagonal Planet',
  'Plated Planet',
  'Scaly Planet',
  'Mechanical Planet',
  'Metallic Planet',
  'Metallurgic Planet',
  'Bubbling Planet',
  'Frothing Planet',
  'Foaming Planet',
  'Columned Planet',
  'Sharded Planet',
  'Pillared Planet',
  'Planet of Light',
  'Crimson Planet',
  'Malfunctioning Planet',
  'Breached Planet',
  'Infected Planet',
  '[REDACTED] Planet',
  'Glassy Planet',
  'Thirsty Planet',
  'Doomed Planet',
  'Erased Planet',
  'Temporary Planet',
  'Corrupted Planet',
  'Planetary Anomaly',
  'Charred Planet',
  'Arid Planet',
  'Scorched Planet',
  'Hot Planet',
  'Fiery Planet',
  'Boiling Planet',
  'High Temperature Planet',
  'Torrid Planet',
  'Incandescent Planet',
  'Scalding Planet',
  'Frozen Planet',
  'Icebound Planet',
  'Arctic Planet',
  'Glacial Planet',
  'Sub-zero Planet',
  'Icy Planet',
  'Frostbound Planet',
  'Freezing Planet',
  'Hiemal Planet',
  'Hyperborean Planet',
  'Irradiated Planet',
  'Radioactive Planet',
  'Contaminated Planet',
  'Nuclear Planet',
  'Isotopic Planet',
  'Decaying Nuclear Planet',
  'Gamma-Intensive Planet',
  'High Radio Source Planet',
  'Supercritical Planet',
  'High Energy Planet',
  'Toxic Planet',
  'Poisonous Planet',
  'Noxious Planet',
  'Corrosive Planet',
  'Acidic Planet',
  'Caustic Planet',
  'Acrid Planet',
  'Blighted Planet',
  'Miasmatic Planet',
  'Rotting Planet',
  'Barren Planet',
  'Desert Planet',
  'Rocky Planet',
  'Bleak Planet',
  'Parched Planet',
  'Abandoned Planet',
  'Dusty Planet',
  'Desolate Planet',
  'Wind-swept Planet',
  'Marshy Planet',
  'Swamp Planet',
  'Tropical Planet',
  'Foggy Planet',
  'Misty Planet',
  'Boggy Planet',
  'Quagmire Planet',
  'Hazy Planet',
  'Cloudy Planet',
  'Vapour Planet',
  'Reeking Planet',
  'Murky Planet',
  'Damp Planet',
  'Endless Morass',
  'Lava Planet',
  'Magma Planet',
  'Erupting Planet',
  'Volcanic Planet',
  'Ash-Shrouded Planet',
  'Ashen Planet',
  'Tectonic Planet',
  'Unstable Planet',
  'Violent Planet',
  'Molten Planet',
  'Flame-Ruptured Planet',
  'Basalt Planet',
  'Imminent Core Detonation',
  'Obsidian Bead',
  'Lost Red Planet',
  'Chromatic Fog Planet',
  'Scarlet Planet',
  'Blood Planet',
  'Wine Dark Planet',
  'Lost Green Planet',
  'Doomed Jade Planet',
  'Haunted Emeril Planet',
  'Lost Blue Planet',
  'Azure Planet',
  'Cerulean Planet',
  'Ultramarine Planet',
  'Stellar Corruption Detected',
  'Vermillion Globe',
  'Vile Anomaly',
  'Toxic Anomaly',
  'Deathly Green Anomaly',
  'Harsh Blue Globe',
  'Frozen Anomaly',
  'Drowning Planet',
  'Oceanic Planet',
  'Tidal Planet',
  'Waterlocked Planet',
  'Aquatic Planet',
  'Marine Planet',
  'Waterworld',
  'Endless Seas',
  'Infested Planet',
  'Worm-ridden Planet',
  'Tainted Planet',
  'Mutated Planet',
  'Corrupted Planet',
  'Infested Paradise',
  'Toxic Horror',
  'Boiling Doom',
  'Radioactive Abomination',
  'Icy Abhorrence',
  'Xeno-Colony',
  'Caustic Nightmare',
  'Fiery Dreadworld',
  'Frozen Hell',
  'Infected Dustbowl',
  'The Nest',
  'Terrorsphere',
] as const;

const InSpanish = [
  'Planeta muerto',
  'Planeta vacío',
  'Planeta desolado',
  'Planeta sin vida',
  'Planeta olvidado',
  'Planeta incompatible con la vida',
  'Planeta de atmósfera baja',
  'Planeta sin aire',
  'Planeta abandonado',
  'Catástrofe de terraformación',
  'Planeta lluvioso',
  'Planeta verde',
  'Planeta tropical',
  'Planeta verdusco',
  'Planeta herboso',
  'Planeta templado',
  'Planeta húmedo',
  'Planeta abundante en flora',
  'Planeta floreciente',
  'Planeta abundante',
  'Planeta paradisíaco',
  'Planeta en pedazos',
  'Planeta con fracturas',
  'Planeta en fragmentación',
  'Planeta con contornos',
  'Planeta con cableado',
  'Planeta en red',
  'Planeta traqueteante',
  'Planeta vertebral',
  'Planeta de estructura esquelética',
  'Planeta de aleta',
  'Planeta de cuchilla',
  'Planeta con conchas',
  'Planeta con hongos',
  'Planeta de esporas',
  'Planeta con cubierta',
  'Planeta de hueso',
  'Planeta en petrificación',
  'Planeta en calcificación',
  'Planeta con fisuras',
  'Planeta con brecha',
  'Planeta hexagonal',
  'Planeta con coraza',
  'Planeta en escamación',
  'Planeta con mecánica',
  'Planeta de metal',
  'Planeta con metales',
  'Planeta burbujeante',
  'Planeta con espuma',
  'Planeta espumante',
  'Planeta con columnas',
  'Planeta en fragmentos',
  'Planeta en pilares',
  'Planeta de luz',
  'Planeta carmesí',
  'Planeta disfuncional',
  'Planeta con brecha',
  'Planeta infectado',
  'Planeta [EDITADO]',
  'Planeta vidrioso',
  'Planeta sediento',
  'Planeta condenado',
  'Planeta exterminado',
  'Planeta temporal',
  'Planeta corrompido',
  'Anomalía planetaria',
  'Planeta carbonizado',
  'Planeta árido',
  'Planeta abrasado',
  'Planeta caluroso',
  'Planeta tórrido',
  'Planeta sofocante',
  'Planeta de altas temperaturas',
  'Planeta caliente',
  'Planeta incandescente',
  'Planeta hirviente',
  'Planeta congelado',
  'Planeta escarchado',
  'Planeta ártico',
  'Planeta glacial',
  'Planeta subcero',
  'Planeta algente',
  'Planeta con escarcha',
  'Planeta inclemente',
  'Planeta hiemal',
  'Planeta septentrional',
  'Planeta irradiado',
  'Planeta radiactivo',
  'Planeta contaminado',
  'Planeta nuclear',
  'Planeta molecular',
  'Planeta nuclear decadente',
  'Planeta de intensidad gamma',
  'Planeta de alta radiación',
  'Planeta bullente',
  'Planeta de gran energía',
  'Planeta tóxico',
  'Planeta venenoso',
  'Planeta nocivo',
  'Planeta corrosivo',
  'Planeta de clima ácido',
  'Planeta ardiente',
  'Planeta acre',
  'Planeta en ruinas',
  'Planeta emanante',
  'Planeta débil',
  'Planeta desierto',
  'Planeta rocoso',
  'Planeta sombrío',
  'Planeta seco',
  'Planeta estéril',
  'Planeta polvoriento',
  'Planeta desolado',
  'Planeta barrido por el viento',
  'Planeta pantanoso',
  'Planeta en pantano',
  'Planeta tropical',
  'Planeta brumoso',
  'Planeta nebuloso',
  'Planeta pantanoso',
  'Planeta en ciénaga',
  'Planeta nebuloso',
  'Planeta nublado',
  'Planeta de vapor',
  'Planeta nauseabundo',
  'Planeta turbio',
  'Planeta húmedo',
  'Marisma interminable',
  'Planeta de lava',
  'Planeta de magma',
  'Planeta en erupción',
  'Planeta volcánico',
  'Planeta cubierto de ceniza',
  'Planeta ceniciento',
  'Planeta tectónico',
  'Planeta inestable',
  'Planeta violento',
  'Planeta en fusión',
  'Planeta de llama rota',
  'Planeta basáltico',
  'Detonación inminente del núcleo',
  'Perla obsidiana',
  'Planeta rojo perdido',
  'Planeta de niebla cromática',
  'Planeta escarlata',
  'Planeta de sangre',
  'Planeta color vino oscuro',
  'Planeta verde perdido',
  'Planeta jade condenado',
  'Planeta emeril atormentado',
  'Planeta azul perdido',
  'Planeta azul celeste',
  'Planeta cerúleo',
  'Planeta ultramarino',
  'Corrupción estelar detectada',
  'Globo bermellón',
  'Anomalía vil',
  'Anomalía tóxica',
  'Anomalía de muerte verde',
  'Globo azul extremo',
  'Anomalía helada',
  'Planeta ahogado',
  'Planeta oceánico',
  'Planeta de mareas',
  'Planeta sumergido',
  'Planeta acuático',
  'Planeta marino',
  'Mundo acuático',
  'Maelstrom infinito',
  'Planeta infestado',
  'Planeta invadido por gusanos',
  'Planeta contaminado',
  'Planeta mutado',
  'Planeta corrompido',
  'Paraíso infestado',
  'Horror tóxico',
  'Destrucción hirviente',
  'Abominación radiactiva',
  'Abominación helada',
  'Colonia xeno',
  'Pesadilla cáustica',
  'Mundo de terror ígneo',
  'Infierno helado',
  'Polvorienta infección',
  'El nido',
  'Terrorfera',
] as const;

export const mappedPlanetDescriptors: SelectOption[] = InSpanish.map((mode, index) => ({
  label: mode,
  value: InEnglish[index],
}));

const InEnglishMoon = [
  'Dead Moon',
  'Empty Moon',
  'Desolate Moon',
  'Lifeless Moon',
  'Forsaken Moon',
  'Life-Incompatible Moon',
  'Low Atmosphere Moon',
  'Airless Moon',
  'Abandoned Moon',
  'Terraforming Catastrophe Moon',
  'Rainy Moon',
  'Verdant Moon',
  'Tropical Moon',
  'Viridescent Moon',
  'Grassy Moon',
  'Temperate Moon',
  'Humid Moon',
  'Overgrown Moon',
  'Flourishing Moon',
  'Bountiful Moon',
  'Paradise Moon',
  'Shattered Moon',
  'Fractured Moon',
  'Fragmented Moon',
  'Contoured Moon',
  'Cabled Moon',
  'Webbed Moon',
  'Rattling Moon',
  'Spined Moon',
  'Skeletal Moon',
  'Finned Moon',
  'Bladed Moon',
  'Shell-Strewn Moon',
  'Fungal Moon',
  'Sporal Moon',
  'Capped Moon',
  'Ossified Moon',
  'Petrified Moon',
  'Calcified Moon',
  'Fissured Moon',
  'Breached Moon',
  'Hexagonal Moon',
  'Plated Moon',
  'Scaly Moon',
  'Mechanical Moon',
  'Metallic Moon',
  'Metallurgic Moon',
  'Bubbling Moon',
  'Frothing Moon',
  'Foaming Moon',
  'Columned Moon',
  'Sharded Moon',
  'Pillared Moon',
  'Moon of Light',
  'Crimson Moon',
  'Malfunctioning Moon',
  'Breached Moon',
  'Infected Moon',
  '[REDACTED] Moon',
  'Glassy Moon',
  'Thirsty Moon',
  'Doomed Moon',
  'Erased Moon',
  'Temporary Moon',
  'Corrupted Moon',
  'Moon Anomaly',
  'Charred Moon',
  'Arid Moon',
  'Scorched Moon',
  'Hot Moon',
  'Fiery Moon',
  'Boiling Moon',
  'High Temperature Moon',
  'Torrid Moon',
  'Incandescent Moon',
  'Scalding Moon',
  'Frozen Moon',
  'Icebound Moon',
  'Arctic Moon',
  'Glacial Moon',
  'Sub-zero Moon',
  'Icy Moon',
  'Frostbound Moon',
  'Freezing Moon',
  'Hiemal Moon',
  'Hyperborean Moon',
  'Irradiated Moon',
  'Radioactive Moon',
  'Contaminated Moon',
  'Nuclear Moon',
  'Isotopic Moon',
  'Decaying Nuclear Moon',
  'Gamma-Intensive Moon',
  'High Radio Source Moon',
  'Supercritical Moon',
  'High Energy Moon',
  'Toxic Moon',
  'Poisonous Moon',
  'Noxious Moon',
  'Corrosive Moon',
  'Acidic Moon',
  'Caustic Moon',
  'Acrid Moon',
  'Blighted Moon',
  'Miasmatic Moon',
  'Rotting Moon',
  'Barren Moon',
  'Desert Moon',
  'Rocky Moon',
  'Bleak Moon',
  'Parched Moon',
  'Abandoned Moon',
  'Dusty Moon',
  'Desolate Moon',
  'Wind-swept Moon',
  'Marshy Moon',
  'Swamp Moon',
  'Tropical Moon',
  'Foggy Moon',
  'Misty Moon',
  'Boggy Moon',
  'Quagmire Moon',
  'Hazy Moon',
  'Cloudy Moon',
  'Vapour Moon',
  'Reeking Moon',
  'Murky Moon',
  'Damp Moon',
  'Endless Morass',
  'Lava Moon',
  'Magma Moon',
  'Erupting Moon',
  'Volcanic Moon',
  'Ash-Shrouded Moon',
  'Ashen Moon',
  'Tectonic Moon',
  'Unstable Moon',
  'Violent Moon',
  'Molten Moon',
  'Flame-Ruptured Moon',
  'Basalt Moon',
  'Imminent Core Detonation',
  'Obsidian Bead',
  'Lost Red Moon',
  'Chromatic Fog Moon',
  'Scarlet Moon',
  'Blood Moon',
  'Wine Dark Moon',
  'Lost Green Moon',
  'Doomed Jade Moon',
  'Haunted Emeril Moon',
  'Lost Blue Moon',
  'Azure Moon',
  'Cerulean Moon',
  'Ultramarine Moon',
  'Stellar Corruption Detected',
  'Vermillion Globe',
  'Vile Anomaly',
  'Toxic Anomaly',
  'Deathly Green Anomaly',
  'Harsh Blue Globe',
  'Frozen Anomaly',
  'Drowning Moon',
  'Oceanic Moon',
  'Tidal Moon',
  'Waterlocked Moon',
  'Aquatic Moon',
  'Marine Moon',
  'Waterworld',
  'Endless Seas',
  'Infested Moon',
  'Worm-ridden Moon',
  'Tainted Moon',
  'Mutated Moon',
  'Corrupted Moon',
  'Infested Paradise',
  'Toxic Horror',
  'Boiling Doom',
  'Radioactive Abomination',
  'Icy Abhorrence',
  'Xeno-Colony',
  'Caustic Nightmare',
  'Fiery Dreadworld',
  'Frozen Hell',
  'Infected Dustbowl',
  'The Nest',
  'Terrorsphere',
] as const;

const InSpanishMoon = [
  'Luna muerta',
  'Luna vacía',
  'Luna desolada',
  'Luna yermo',
  'Luna olvidada',
  'Luna incompatible con la vida',
  'Luna de atmósfera baja',
  'Luna sin aire',
  'Luna abandonada',
  'Catástrofe de terraformación de la luna',
  'Luna lluviosa',
  'Luna verde',
  'Luna tropical',
  'Luna verdusca',
  'Luna herbosa',
  'Luna templada',
  'Luna húmeda',
  'Luna abundante en flora',
  'Luna floreciente',
  'Luna abundante',
  'Luna paradisíaca',
  'Luna en pedazos',
  'Luna con fracturas',
  'Luna en fragmentación',
  'Luna con contornos',
  'Luna con cableado',
  'Luna en red',
  'Luna traqueteante',
  'Luna vertebral',
  'Luna de estructura esquelética',
  'Luna de aleta',
  'Luna de cuchilla',
  'Luna con conchas',
  'Luna con hongos',
  'Luna de esporas',
  'Luna con cubierta',
  'Luna de hueso',
  'Luna en petrificación',
  'Luna en calcificación',
  'Luna con fisuras',
  'Luna con brecha',
  'Luna hexagonal',
  'Luna con coraza',
  'Luna en escamación',
  'Luna con mecánica',
  'Luna de metal',
  'Luna con metales',
  'Luna burbujeante',
  'Luna con espuma',
  'Luna espumante',
  'Luna con columnas',
  'Luna en fragmentos',
  'Luna en pilares',
  'Luna de luz',
  'Luna carmesí',
  'Luna disfuncional',
  'Luna con brecha',
  'Luna infectada',
  'Luna [EDITADA]',
  'Luna vidriosa',
  'Luna sedienta',
  'Luna condenada',
  'Luna exterminada',
  'Luna temporal',
  'Luna corrompida',
  'Anomalía lunar',
  'Luna carbonizada',
  'Luna árida',
  'Luna abrasada',
  'Luna calurosa',
  'Luna tórrida',
  'Luna sofocante',
  'Luna de altas temperaturas',
  'Luna caliente',
  'Luna incandescente',
  'Luna hirviente',
  'Luna congelada',
  'Luna escarchada',
  'Luna ártica',
  'Luna glacial',
  'Luna subcero',
  'Luna algente',
  'Luna con escarcha',
  'Luna inclemente',
  'Luna hiemal',
  'Luna septentrional',
  'Luna irradiada',
  'Luna radiactiva',
  'Luna contaminada',
  'Luna nuclear',
  'Luna molecular',
  'Luna nuclear decadente',
  'Luna de intensidad gamma',
  'Luna de alta radiación',
  'Luna bullente',
  'Luna de gran energía',
  'Luna tóxica',
  'Luna venenosa',
  'Luna nociva',
  'Luna corrosiva',
  'Luna de clima ácido',
  'Luna ardiente',
  'Luna acre',
  'Luna en ruinas',
  'Luna emanante',
  'Luna débil',
  'Luna desierto',
  'Luna rocoso',
  'Luna sombría',
  'Luna seca',
  'Luna estéril',
  'Luna polvorienta',
  'Luna desolada',
  'Luna barrida por el viento',
  'Luna pantanosa',
  'Luna en pantano',
  'Luna tropical',
  'Luna brumosa',
  'Luna nebulosa',
  'Luna pantanosa',
  'Luna en ciénaga',
  'Luna nebulosa',
  'Luna nublada',
  'Luna de vapor',
  'Luna nauseabunda',
  'Luna turbia',
  'Luna húmeda',
  'Marisma interminable',
  'Luna de lava',
  'Luna de magma',
  'Luna en erupción',
  'Luna volcánica',
  'Luna cubierto de ceniza',
  'Luna cenicienta',
  'Luna tectónica',
  'Luna inestable',
  'Luna violenta',
  'Luna en fusión',
  'Luna de llama rota',
  'Luna basáltica',
  'Detonación inminente del núcleo',
  'Perla obsidiana',
  'Luna roja perdida',
  'Luna de niebla cromática',
  'Luna escarlata',
  'Luna de sangre',
  'Luna color vino oscuro',
  'Luna verde perdida',
  'Luna jade condenada',
  'Luna emeril atormentada',
  'Luna azul perdida',
  'Luna azul celeste',
  'Luna cerúlea',
  'Luna ultramarina',
  'Corrupción estelar detectada',
  'Globo bermellón',
  'Anomalía vil',
  'Anomalía tóxica',
  'Anomalía de muerte verde',
  'Globo azul extremo',
  'Anomalía helada',
  'Luna ahogada',
  'Luna oceánica',
  'Luna de mareas',
  'Luna sumergida',
  'Luna acuática',
  'Luna marina',
  'Mundo acuático',
  'Maelstrom infinito',
  'Luna infestada',
  'Luna invadida por gusanos',
  'Luna contaminada',
  'Luna mutada',
  'Luna corrompida',
  'Paraíso infestado',
  'Horror tóxico',
  'Destrucción hirviente',
  'Abominación radiactiva',
  'Abominación helada',
  'Colonia xeno',
  'Pesadilla cáustica',
  'Mundo de terror ígneo',
  'Infierno helado',
  'Polvorienta infección',
  'El nido',
  'Terrorfera',
] as const;

const InEnglishGiant = [
  'Dead Giant',
  'Empty Giant',
  'Desolate Giant',
  'Lifeless Giant',
  'Forsaken Giant',
  'Life-Incompatible Giant',
  'Low Atmosphere Giant',
  'Airless Giant',
  'Abandoned Giant',
  'Terraforming Catastrophe',
  'Rainy Giant',
  'Verdant Giant',
  'Tropical Giant',
  'Viridescent Giant',
  'Grassy Giant',
  'Temperate Giant',
  'Humid Giant',
  'Overgrown Giant',
  'Flourishing Giant',
  'Bountiful Giant',
  'Paradise Giant',
  'Shattered Giant',
  'Fractured Giant',
  'Fragmented Giant',
  'Contoured Giant',
  'Cabled Giant',
  'Webbed Giant',
  'Rattling Giant',
  'Spined Giant',
  'Skeletal Giant',
  'Finned Giant',
  'Bladed Giant',
  'Shell-Strewn Giant',
  'Fungal Giant',
  'Sporal Giant',
  'Capped Giant',
  'Ossified Giant',
  'Petrified Giant',
  'Calcified Giant',
  'Fissured Giant',
  'Breached Giant',
  'Hexagonal Giant',
  'Plated Giant',
  'Scaly Giant',
  'Mechanical Giant',
  'Metallic Giant',
  'Metallurgic Giant',
  'Bubbling Giant',
  'Frothing Giant',
  'Foaming Giant',
  'Columned Giant',
  'Sharded Giant',
  'Pillared Giant',
  'Giant of Light',
  'Crimson Giant',
  'Malfunctioning Giant',
  'Breached Giant',
  'Infected Giant',
  '[REDACTED] Giant',
  'Glassy Giant',
  'Thirsty Giant',
  'Doomed Giant',
  'Erased Giant',
  'Temporary Giant',
  'Corrupted Giant',
  'Planetary Anomaly',
  'Charred Giant',
  'Arid Giant',
  'Scorched Giant',
  'Hot Giant',
  'Fiery Giant',
  'Boiling Giant',
  'High Temperature Giant',
  'Torrid Giant',
  'Incandescent Giant',
  'Scalding Giant',
  'Frozen Giant',
  'Icebound Giant',
  'Arctic Giant',
  'Glacial Giant',
  'Sub-zero Giant',
  'Icy Giant',
  'Frostbound Giant',
  'Freezing Giant',
  'Hiemal Giant',
  'Hyperborean Giant',
  'Irradiated Giant',
  'Radioactive Giant',
  'Contaminated Giant',
  'Nuclear Giant',
  'Isotopic Giant',
  'Decaying Nuclear Giant',
  'Gamma-Intensive Giant',
  'High Radio Source Giant',
  'Supercritical Giant',
  'High Energy Giant',
  'Toxic Giant',
  'Poisonous Giant',
  'Noxious Giant',
  'Corrosive Giant',
  'Acidic Giant',
  'Caustic Giant',
  'Acrid Giant',
  'Blighted Giant',
  'Miasmatic Giant',
  'Rotting Giant',
  'Barren Giant',
  'Desert Giant',
  'Rocky Giant',
  'Bleak Giant',
  'Parched Giant',
  'Abandoned Giant',
  'Dusty Giant',
  'Desolate Giant',
  'Wind-swept Giant',
  'Marshy Giant',
  'Swamp Giant',
  'Tropical Giant',
  'Foggy Giant',
  'Misty Giant',
  'Boggy Giant',
  'Quagmire Giant',
  'Hazy Giant',
  'Cloudy Giant',
  'Vapour Giant',
  'Reeking Giant',
  'Murky Giant',
  'Damp Giant',
  'Endless Morass',
  'Lava Giant',
  'Magma Giant',
  'Erupting Giant',
  'Volcanic Giant',
  'Ash-Shrouded Giant',
  'Ashen Giant',
  'Tectonic Giant',
  'Unstable Giant',
  'Violent Giant',
  'Molten Giant',
  'Flame-Ruptured Giant',
  'Basalt Giant',
  'Imminent Core Detonation',
  'Obsidian Bead',
  'Lost Red Giant',
  'Chromatic Fog Giant',
  'Scarlet Giant',
  'Blood Giant',
  'Wine Dark Giant',
  'Lost Green Giant',
  'Doomed Jade Giant',
  'Haunted Emeril Giant',
  'Lost Blue Giant',
  'Azure Giant',
  'Cerulean Giant',
  'Ultramarine Giant',
  'Stellar Corruption Detected',
  'Vermillion Globe',
  'Vile Anomaly',
  'Toxic Anomaly',
  'Deathly Green Anomaly',
  'Harsh Blue Globe',
  'Frozen Anomaly',
  'Drowning Giant',
  'Oceanic Giant',
  'Tidal Giant',
  'Waterlocked Giant',
  'Aquatic Giant',
  'Marine Giant',
  'Waterworld',
  'Endless Seas',
  'Infested Giant',
  'Worm-ridden Giant',
  'Tainted Giant',
  'Mutated Giant',
  'Corrupted Giant',
  'Infested Paradise',
  'Toxic Horror',
  'Boiling Doom',
  'Radioactive Abomination',
  'Icy Abhorrence',
  'Xeno-Colony',
  'Caustic Nightmare',
  'Fiery Dreadworld',
  'Frozen Hell',
  'Infected Dustbowl',
  'The Nest',
  'Terrorsphere',
] as const;

const InSpanishGiant = [
  'Gigante muerto',
  'Gigante vacío',
  'Gigante desolado',
  'Gigante sin vida',
  'Gigante olvidado',
  'Gigante incompatible con la vida',
  'Gigante de atmósfera baja',
  'Gigante sin aire',
  'Gigante abandonado',
  'Catástrofe de terraformación',
  'Gigante lluvioso',
  'Gigante verde',
  'Gigante tropical',
  'Gigante verdusco',
  'Gigante herboso',
  'Gigante templado',
  'Gigante húmedo',
  'Gigante abundante en flora',
  'Gigante floreciente',
  'Gigante abundante',
  'Gigante paradisíaco',
  'Gigante en pedazos',
  'Gigante con fracturas',
  'Gigante en fragmentación',
  'Gigante con contornos',
  'Gigante con cableado',
  'Gigante en red',
  'Gigante traqueteante',
  'Gigante vertebral',
  'Gigante de estructura esquelética',
  'Gigante de aleta',
  'Gigante de cuchilla',
  'Gigante con conchas',
  'Gigante con hongos',
  'Gigante de esporas',
  'Gigante con cubierta',
  'Gigante de hueso',
  'Gigante en petrificación',
  'Gigante en calcificación',
  'Gigante con fisuras',
  'Gigante con brecha',
  'Gigante hexagonal',
  'Gigante con coraza',
  'Gigante en escamación',
  'Gigante con mecánica',
  'Gigante de metal',
  'Gigante con metales',
  'Gigante burbujeante',
  'Gigante con espuma',
  'Gigante espumante',
  'Gigante con columnas',
  'Gigante en fragmentos',
  'Gigante en pilares',
  'Gigante de luz',
  'Gigante carmesí',
  'Gigante disfuncional',
  'Gigante con brecha',
  'Gigante infectado',
  'Gigante [EDITADO]',
  'Gigante vidrioso',
  'Gigante sediento',
  'Gigante condenado',
  'Gigante exterminado',
  'Gigante temporal',
  'Gigante corrompido',
  'Anomalía planetaria',
  'Gigante carbonizado',
  'Gigante árido',
  'Gigante abrasado',
  'Gigante caluroso',
  'Gigante tórrido',
  'Gigante sofocante',
  'Gigante de altas temperaturas',
  'Gigante caliente',
  'Gigante incandescente',
  'Gigante hirviente',
  'Gigante congelado',
  'Gigante escarchado',
  'Gigante ártico',
  'Gigante glacial',
  'Gigante subcero',
  'Gigante algente',
  'Gigante con escarcha',
  'Gigante inclemente',
  'Gigante hiemal',
  'Gigante septentrional',
  'Gigante irradiado',
  'Gigante radiactivo',
  'Gigante contaminado',
  'Gigante nuclear',
  'Gigante molecular',
  'Gigante nuclear decadente',
  'Gigante de intensidad gamma',
  'Gigante de alta radiación',
  'Gigante bullente',
  'Gigante de gran energía',
  'Gigante tóxico',
  'Gigante venenoso',
  'Gigante nocivo',
  'Gigante corrosivo',
  'Gigante de clima ácido',
  'Gigante ardiente',
  'Gigante acre',
  'Gigante en ruinas',
  'Gigante emanante',
  'Gigante débil',
  'Gigante desierto',
  'Gigante rocoso',
  'Gigante sombrío',
  'Gigante seco',
  'Gigante estéril',
  'Gigante polvoriento',
  'Gigante desolado',
  'Gigante barrido por el viento',
  'Gigante pantanoso',
  'Gigante en pantano',
  'Gigante tropical',
  'Gigante brumoso',
  'Gigante nebuloso',
  'Gigante pantanoso',
  'Gigante en ciénaga',
  'Gigante nebuloso',
  'Gigante nublado',
  'Gigante de vapor',
  'Gigante nauseabundo',
  'Gigante turbio',
  'Gigante húmedo',
  'Marisma interminable',
  'Gigante de lava',
  'Gigante de magma',
  'Gigante en erupción',
  'Gigante volcánico',
  'Gigante cubierto de ceniza',
  'Gigante ceniciento',
  'Gigante tectónico',
  'Gigante inestable',
  'Gigante violento',
  'Gigante en fusión',
  'Gigante de llama rota',
  'Gigante basáltico',
  'Detonación inminente del núcleo',
  'Perla obsidiana',
  'Gigante rojo perdido',
  'Gigante de niebla cromática',
  'Gigante escarlata',
  'Gigante de sangre',
  'Gigante color vino oscuro',
  'Gigante verde perdido',
  'Gigante jade condenado',
  'Gigante emeril atormentado',
  'Gigante azul perdido',
  'Gigante azul celeste',
  'Gigante cerúleo',
  'Gigante ultramarino',
  'Corrupción estelar detectada',
  'Globo bermellón',
  'Anomalía vil',
  'Anomalía tóxica',
  'Anomalía de muerte verde',
  'Globo azul extremo',
  'Anomalía helada',
  'Gigante ahogado',
  'Gigante oceánico',
  'Gigante de mareas',
  'Gigante sumergido',
  'Gigante acuático',
  'Gigante marino',
  'Mundo acuático',
  'Maelstrom infinito',
  'Gigante infestado',
  'Gigante invadido por gusanos',
  'Gigante contaminado',
  'Gigante mutado',
  'Gigante corrompido',
  'Paraíso infestado',
  'Horror tóxico',
  'Destrucción hirviente',
  'Abominación radiactiva',
  'Abominación helada',
  'Colonia xeno',
  'Pesadilla cáustica',
  'Mundo de terror ígneo',
  'Infierno helado',
  'Polvorienta infección',
  'El nido',
  'Terrorfera',
] as const;

export const mappedMoonDescriptors: SelectOption[] = InSpanishMoon.map((mode, index) => ({
  label: mode,
  value: InEnglishMoon[index],
}));

export const mappedGiantDescriptors: SelectOption[] = InSpanishGiant.map((mode, index) => ({
  label: mode,
  value: InEnglishGiant[index],
}));
