import type { SelectOption } from '@/types/selectInputOptions';

const InEnglish = [
  '',
  'Copper',
  'Cadmium',
  'Emeril',
  'Indium',
  'Activated Copper',
  'Activated Cadmium',
  'Activated Emeril',
  'Activated Indium',
  'Ammonia',
  'Dioxite',
  'Paraffinium',
  'Phosphorus',
  'Pyrite',
  'Uranium',
  'Silver',
  'Gold',
  'Magnetised Ferrite',
  'Sodium',
  'Cobalt',
  'Salt',
  'Star Bulb',
  'Cactus Flesh',
  'Gamma Root',
  'Fungal Mould',
  'Frost Crystal',
  'Solanium',
  'Mordite',
  'Faecium',
  'Ancient Bones',
  'Salvageable Scrap',
  'Rusted Metal',
  'Basalt',
  'Quartzite',
  'Activated Quartzite',
] as const;

const InSpanish = [
  '',
  'Cobre',
  'Cadmio',
  'Emerilio',
  'Indio',
  'Cobre Activado',
  'Cadmio Activado',
  'Emerilio Activado',
  'Indio Activado',
  'Amonio',
  'Dioxita',
  'Parafinio',
  'Fósforo',
  'Pirita',
  'Uranio',
  'Plata',
  'Oro',
  'Ferrita imantada',
  'Sodio',
  'Cobalto',
  'Sal',
  'Bulbo Estelar',
  'Carne de Cactus',
  'Raíz de gamma',
  'Moho fúngico',
  'Cristal de escarcha',
  'Solanio',
  'Mordita',
  'Hecesio',
  'Huesos antiguos',
  'Chatarra recuperable',
  'Metal oxidado',
  'Basalto',
  'Cuarcita',
  'Cuarcita Activada',
] as const;


export const mappedResourcesOptions: SelectOption[] = InSpanish.map((mode, index) => ({
  label: mode,
  value: InEnglish[index],
}));
