export const mappedSystemConflict = [
  {
    groupLabel: 'T3',
    label: 'T3',
    items: [
      { label: 'Agresivo', value: '★★★ (Aggressive)' },
      { label: 'Inquietante', value: '★★★ (Alarming)' },
      { label: 'En guerra', value: '★★★ (At War)' },
      { label: 'Crítico', value: '★★★ (Critical)' },
      { label: 'Peligroso', value: '★★★ (Dangerous)' },
      { label: 'Destructivo', value: '★★★ (Destructive)' },
      { label: 'Formidable', value: '★★★ (Formidable)' },
      { label: 'Alto', value: '★★★ (High)' },
      { label: 'Anárquico', value: '★★★ (Lawless)' },
      { label: 'Arriesgado', value: '★★★ (Perilous)' },
    ],
  },
  {
    groupLabel: 'T2',
    label: 'T2',
    items: [
      { label: 'Beligerante', value: '★★ (Belligerent)' },
      { label: 'Tempestuoso', value: '★★ (Boisterous)' },
      { label: 'Ingobernable', value: '★★ (Fractious)' },
      { label: 'Intermitente', value: '★★ (Intermittent)' },
      { label: 'Medio', value: '★★ (Medium)' },
      { label: 'Tumultuoso', value: '★★ (Rowdy)' },
      { label: 'Esporádico', value: '★★ (Sporadic)' },
      { label: 'Alterable', value: '★★ (Testy)' },
      { label: 'Alborotado', value: '★★ (Unruly)' },
      { label: 'Inestable', value: '★★ (Unstable)' },
    ],
  },
  {
    groupLabel: 'T1',
    label: 'T1',
    items: [
      { label: 'Moderado', value: '★ (Gentle)' },
      { label: 'Bajo', value: '★ (Low)' },
      { label: 'Apacible', value: '★ (Mild)' },
      { label: 'Pacífico', value: '★ (Peaceful)' },
      { label: 'Relajado', value: '★ (Relaxed)' },
      { label: 'Estable', value: '★ (Stable)' },
      { label: 'Tranquilo', value: '★ (Tranquil)' },
      { label: 'Insignificante', value: '★ (Trivial)' },
      { label: 'Sin amenazas', value: '★ (Unthreatening)' },
      { label: 'Sin problemas', value: '★ (Untroubled)' },
    ],
  },
  {
    groupLabel: 'Pirata',
    label: 'Pirata',
    items: [{ label: 'Piratas bajo control', value: '💀 (Pirate Controlled)' }],
  },
  {
    groupLabel: 'Abandonado/Inexplorado',
    label: 'Abandonado/Inexplorado',
    items: [{ label: 'Datos no disponibles', value: 'Data Unavailable' }],
  },
];
